/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface EdmbnCalendar {
    /**
    * Calendar locale
    */
    'locale': any;
    /**
    * Calendar month
    */
    'month': number;
    /**
    * Type of calendar
    */
    'type': string;
    /**
    * Calendar year
    */
    'year': number;
  }
}

declare global {


  interface HTMLEdmbnCalendarElement extends Components.EdmbnCalendar, HTMLStencilElement {}
  var HTMLEdmbnCalendarElement: {
    prototype: HTMLEdmbnCalendarElement;
    new (): HTMLEdmbnCalendarElement;
  };
  interface HTMLElementTagNameMap {
    'edmbn-calendar': HTMLEdmbnCalendarElement;
  }
}

declare namespace LocalJSX {
  interface EdmbnCalendar extends JSXBase.HTMLAttributes<HTMLEdmbnCalendarElement> {
    /**
    * Calendar locale
    */
    'locale'?: any;
    /**
    * Calendar month
    */
    'month'?: number;
    /**
    * Type of calendar
    */
    'type'?: string;
    /**
    * Calendar year
    */
    'year'?: number;
  }

  interface IntrinsicElements {
    'edmbn-calendar': EdmbnCalendar;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


